services:
  flask_app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql # mysql コンテナに依存
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3330:3306" # ホストの3330をコンテナの3306(MySQLデフォルト)にマッピング
    volumes:
      - mysql_data:/var/lib/mysql # 永続化するボリューム
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 初期化スクリプト
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
    driver: local
